# Contao configuration
contao:
    #prepend_locale: true
    url_suffix: ''
    image:
        imagine_options:
            jpeg_quality: 100
# Security configuration
nelmio_security:
    xss_protection:
        enabled: true
        mode_block: true
    forced_ssl:
        enabled: true
        hsts_max_age: 2592000
        hsts_subdomains: true
        redirect_status_code: 301
    csp:
        enabled: true
        hash:
            algorithm: sha256
        enforce:
            level1_fallback: false
            img-src:
                - '* data: unsafe-inline'
            default-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'
            script-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'
